version: '3.8'
services:
  back:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - DB_CONNECTION_STRING=mysql+pymysql://root:root@db:3306/ubeer
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ubeer
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-uroot", "-proot"]
      interval: 3s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - "8080:8080"