version: '3.8'
services:
  back:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ubeer
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-uroot", "-proot"]
      interval: 3s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - "8080:8080"