name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@3
      - uses: yarn/action-setup@v2
        with:
          version: 7
      - uses: action/setup-node@v3
        with:
          version: 16.x
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn run ci
